#!/bin/bash

# conda activate FICTURE

# based on https://seqscope.github.io/spatula/tools/join_pixel_tsv/
# almost took 2 mins

# 1. Sorting the pixel-level output from FICTURE
# Typically, the pixel-level output TSV files generated by FICTURE are NOT sorted by a single coordinate
# sort the file based on the major axis used to sort the input data 

# If the major axis is Y-axis, use -gk3
# If the major axis is X-axis, use -gk2

FICTURE_save_path=$1
n_factor=$2
train_width=$3

FICTURE_output_path=${FICTURE_save_path}/analysis/nF${n_factor}.d_${train_width}
prefix=nF${n_factor}.d_${train_width}.decode.prj_12.r_4_5

(gzip -cd ${FICTURE_output_path}/${prefix}.pixel.sorted_remove_BARCODE.tsv.gz \
    | head | grep ^#; \
    gzip -cd ${FICTURE_output_path}/${prefix}.pixel.sorted_remove_BARCODE.tsv.gz \
    | grep -v ^# | sort -S 1G -gk3) \
    | gzip -c > ${FICTURE_output_path}/${prefix}.pixel.sorted_by_major_axis.tsv.gz

